# æ¬¢è¿ä½¿ç”¨ TRSS Yunzai Plugin ! ä½œè€…ï¼šæ—¶é›¨ğŸŒŒæ˜Ÿç©º
# æŒ‰ Ctrl+Q Y ä¿å­˜é€€å‡º
# å‚è€ƒï¼šhttps://gitee.com/TimeRainStarSky/TRSS-Plugin

ChatGPT:
  api: "" # ç§äºº API åœ°å€
  tokenapi: "" # Token API åœ°å€
  username: "" # OpenAI è´¦å·
  password: "" # OpenAI å¯†ç 
  sessionToken: ""